// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHH3o5qw_nG5zSqYPwoQ7vHfx8Uo1Jmo',
    appId: '1:466759886255:web:26553a975936f8ad27fb5a',
    messagingSenderId: '466759886255',
    projectId: 'lofoiiti-65589',
    authDomain: 'lofoiiti-65589.firebaseapp.com',
    storageBucket: 'lofoiiti-65589.appspot.com',
    measurementId: 'G-F0XFVW2LWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG4UnKP9D_s9k3sbPoMkxc7DiwO2R8Xx8',
    appId: '1:466759886255:android:9a2691f3c4b176f227fb5a',
    messagingSenderId: '466759886255',
    projectId: 'lofoiiti-65589',
    storageBucket: 'lofoiiti-65589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIhSDjR2kpUX39ZutkEDzKFTbhHVTcV0k',
    appId: '1:466759886255:ios:5305a617ac000bf627fb5a',
    messagingSenderId: '466759886255',
    projectId: 'lofoiiti-65589',
    storageBucket: 'lofoiiti-65589.appspot.com',
    androidClientId: '466759886255-d461i9esq7182qrs7ltsf7nk0f59b3p2.apps.googleusercontent.com',
    iosClientId: '466759886255-bk6p87mairjteogf3s6ugkcan3qol8o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lofo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIhSDjR2kpUX39ZutkEDzKFTbhHVTcV0k',
    appId: '1:466759886255:ios:50ec1acd4cfef68f27fb5a',
    messagingSenderId: '466759886255',
    projectId: 'lofoiiti-65589',
    storageBucket: 'lofoiiti-65589.appspot.com',
    androidClientId: '466759886255-d461i9esq7182qrs7ltsf7nk0f59b3p2.apps.googleusercontent.com',
    iosClientId: '466759886255-u2khcm47afuk3bpncjrd3l2s51opor41.apps.googleusercontent.com',
    iosBundleId: 'com.example.lofo.RunnerTests',
  );
}
